version: '3.1'

services:
  backend:
    build: ../server
    environment:
      MONGODB_URL: mongodb://root:root@mongo:27017/
      MONGODB_DATABASE: trash
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: trash
    ports:
      - "27017:27017" # todo: remove
    volumes:
      - db-data:/data/db

volumes:
  db-data:
